version: 2
updates:
  - package-ecosystem: pip
    directory: /projects/lib-pcg-algopy
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        exclude-patterns:
          # Even when this is a minor or patch bump, it still causes the artifacts to change.allow:
          # In order to keep manual intervention on PRs to a minimum (commit new artifacts),
          #  we are going to have puyapy updates through separate PRs.
          - puyapy
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /projects/lib-pcg-algots
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        exclude-patterns:
          - @algorandfoundation/puya-ts
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /projects/unified-tests
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
