version: 2
updates:
  - package-ecosystem: pip
    directory: /projects/lib-pcg-algopy
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /projects/lib-pcg-algots
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /projects/unified-tests
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
